// src/types.ts

export interface Tag {
    id: string;
    name: string;
}

export interface Note {
    id: string;
    title: string;
    content: string;
    tagIds: string[]; // An array of Tag IDs
    createdAt: number; // Unix timestamp
    updatedAt: number; // Unix timestamp
}

// This is the data shape we'll use when creating or updating a note
// It's a partial Note, as some fields are generated by the API
export type NotePayload = Partial<Omit<Note, 'id'>> & {
    id?: string; // id is optional because a new note won't have one yet
};